name: wa_mi_flutter
description: Migración completa de WaMi a Flutter
version: 1.0.0
publish_to: 'none' # Agregado para evitar publicación accidental

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencias que tenías
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3
  go_router: ^13.2.3
  cupertino_icons: ^1.0.6

  # Dependencias que FALTABAN
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.22
  path_provider: ^2.1.3
  path: ^1.9.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Dependencias de desarrollo que FALTABAN
  drift_dev: ^2.18.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true